/**
 * FACTUTEC - Base de Datos de Clientes y Casos de Éxito
 * Implementaciones de FACTUVENTAS (Básico, MultiCaja y ARCA) en comercios reales
 */

const CLIENTS_DATA = [
  {
    id: "la-previa-del-emis",
    name: "La Previa del Emi´s",
    category: "almacenes",
    categoryName: "Comercios & Almacenes",
    logoImage: "assets/images/la-previa-del-emis-logo.png?v=5",
    logoText: "LPE",
    logoColor: "#db2777",
    logoBg: "#fdf2f8",
    systemInstalled: "FactuVentas + Facturación Electrónica ARCA",
    hardware: "1 Puesto de Caja Rápida",
    location: "Rivadavia, Mendoza",
    year: "2026",
    highlight: "Necesidad de registrar ventas en ARCA con emisión fiscal automática y rápida en caja",
    rating: 5,
    testimonial: "Excelente el sistema FactuVentas con facturación ARCA que nos instalaron Joel y Emanuel. En hora pico cobramos rapidísimo y todos los comprobantes quedan registrados al instante sin complicaciones."
  },
  {
    id: "kema-importaciones",
    name: "Kema Importaciones",
    category: "servicios",
    categoryName: "Tecnología & Importaciones",
    logoImage: "assets/images/kema-importaciones-logo.png?v=5",
    logoText: "KEM",
    logoColor: "#0d9488",
    logoBg: "#f0fdfa",
    systemInstalled: "FactuVentas Avanzado ($250.000)",
    hardware: "1 Puesto de Caja Rápida",
    location: "Junín, Mendoza",
    year: "2026",
    highlight: "Digitalización total: pasaron de registrar ventas y stock en papel a la velocidad del sistema FactuVentas",
    rating: 5,
    testimonial: "Antes anotábamos todo en libretas y el stock era un lío. Con FactuVentas que nos configuraron Joel y Emanuel ahora tenemos el inventario al día y cobramos en segundos. Un cambio abismal para nuestro negocio."
  },
  {
    id: "distribuidora-nahuel",
    name: "Distribuidora Nahuel",
    category: "mayoristas",
    categoryName: "Mayoristas & Distribuidoras",
    logoText: "DN",
    logoColor: "#1d4ed8",
    logoBg: "#eff6ff",
    systemInstalled: "FactuVentas Avanzado ($250.000)",
    hardware: "1 Puesto de Caja Rápida",
    location: "San Martín, Mendoza",
    year: "2026",
    highlight: "Control masivo de inventario, listas de precios por bulto/volumen y despacho ágil de mercadería",
    rating: 5,
    testimonial: "Para una distribuidora el control de stock y los precios mayoristas son clave. FactuVentas nos facilitó el despacho de pedidos y la atención en mostrador. El soporte técnico de FactuTec es de primera."
  },
  {
    id: "supermercado-el-trebol",
    name: "Supermercado El Trébol",
    category: "almacenes",
    categoryName: "Comercios & Almacenes",
    logoText: "SET",
    logoColor: "#047857",
    logoBg: "#d1fae5",
    systemInstalled: "FactuVentas + Facturación ARCA Automática",
    hardware: "2 Cajas Rápidas + Balanza Digital Systel",
    location: "Junín, Mendoza",
    year: "2023",
    highlight: "Conexión directa con balanza para productos a granel y facturación ARCA en cada ticket",
    rating: 5,
    testimonial: "Excelente atención de Joel y Emanuel. Nos dejaron las básculas y las impresoras configuradas funcionando de diez."
  },
  {
    id: "ferreteria-industrial-este",
    name: "Ferretería Industrial Este",
    category: "ferreterias",
    categoryName: "Ferreterías & Corralones",
    logoText: "FIE",
    logoColor: "#b45309",
    logoBg: "#fef3c7",
    systemInstalled: "FactuVentas Avanzado MultiCaja + Factura A4",
    hardware: "Servidor Mostrador + 2 Terminales + Impresora A4",
    location: "Rivadavia, Mendoza",
    year: "2024",
    highlight: "Múltiples listas de precios, cuentas corrientes y módulo de facturas A4 para órdenes de compra",
    rating: 5,
    testimonial: "El módulo para emitir órdenes de compra y facturas en hoja A4 nos vino perfecto para las empresas que nos compran."
  },
  {
    id: "boutique-urbana",
    name: "Boutique Urbana Moda",
    category: "indumentaria",
    categoryName: "Indumentaria & Calzado",
    logoText: "BUM",
    logoColor: "#be185d",
    logoBg: "#fce7f3",
    systemInstalled: "FactuVentas Básico ($150.000)",
    hardware: "1 Puesto Mostrador + Lector de Código de Barras",
    location: "San Martín Centro, Mendoza",
    year: "2024",
    highlight: "Control de inventario de indumentaria, cortes de caja por turno y operación 100% offline",
    rating: 5,
    testimonial: "Super fácil de usar. Pagamos los $150.000 una sola vez y nos olvidamos para siempre de pagar mensualidades."
  },
  {
    id: "corralon-mendoza",
    name: "Corralón Mendoza Materiales",
    category: "ferreterias",
    categoryName: "Ferreterías & Corralones",
    logoText: "CMM",
    logoColor: "#c2410c",
    logoBg: "#ffedd5",
    systemInstalled: "FactuVentas Avanzado + ARCA + Red de Cajas",
    hardware: "4 Puestos en Red + Router Wi-Fi Comercial + 2 Impresoras",
    location: "Palmira, Mendoza",
    year: "2023",
    highlight: "Red local cableada por FactuTec con facturación electrónica ARCA automática en todas las cajas",
    rating: 5,
    testimonial: "FactuTec nos hizo no solo la instalación de FactuVentas sino todo el cableado de red y configuración de routers."
  },
  {
    id: "pizzeria-donatello",
    name: "Pizzería & Resto Donatello",
    category: "gastronomia",
    categoryName: "Gastronomía & Bares",
    logoText: "PRD",
    logoColor: "#b91c1c",
    logoBg: "#fee2e2",
    systemInstalled: "FactuVentas + Facturación ARCA",
    hardware: "PC Mostrador + Impresora Térmica 80mm",
    location: "San Martín, Mendoza",
    year: "2024",
    highlight: "Cortes de caja diarios exactos y facturación electrónica instantánea para delivery y salón",
    rating: 5,
    testimonial: "La velocidad de cobro los fines de semana es tremenda. La instalación fue impecable."
  },
  {
    id: "mayorista-los-andes",
    name: "Mayorista Los Andes",
    category: "mayoristas",
    categoryName: "Mayoristas & Distribuidoras",
    logoText: "MLA",
    logoColor: "#4338ca",
    logoBg: "#e0e7ff",
    systemInstalled: "FactuVentas MultiCaja + ARCA + Factura A4",
    hardware: "5 Cajas en Red + Servidor Dedicado + Backup",
    location: "Godoy Cruz, Mendoza",
    year: "2023",
    highlight: "Sincronización multi-caja en tiempo real con facturación masiva ARCA",
    rating: 5,
    testimonial: "Emanuel y Joel nos armaron la red completa. El monitoreo remoto desde el celular nos permite ver las ventas en vivo."
  },
  {
    id: "cerveceria-artesanal",
    name: "Cervecería & Bar La Estación",
    category: "gastronomia",
    categoryName: "Gastronomía & Bares",
    logoText: "CBE",
    logoColor: "#d97706",
    logoBg: "#fef3c7",
    systemInstalled: "FactuVentas MultiCaja + Red Wi-Fi",
    hardware: "Terminal Mostrador + Caja Barra + Red de Cajas",
    location: "Junín, Mendoza",
    year: "2024",
    highlight: "Gestión de cajas independientes con administración y precios centralizados",
    rating: 5,
    testimonial: "El sistema no falla nunca en pleno servicio nocturno. Una tranquilidad total."
  }
];
