/**
 * FACTUTEC - Base de Datos de Clientes y Casos de Éxito
 * Implementaciones de ELEVENTA (Básico, MultiCaja y ARCA) en comercios reales
 */

const CLIENTS_DATA = [
  {
    id: "distribuidora-cuyo",
    name: "Distribuidora Cuyo Sur",
    category: "mayoristas",
    categoryName: "Mayoristas & Distribuidoras",
    logoText: "DCS",
    logoColor: "#1e40af",
    logoBg: "#dbeafe",
    systemInstalled: "Eleventa Avanzado + Puente Facturación ARCA",
    hardware: "3 Puestos en Red + Lectores Láser + Impresoras 80mm",
    location: "San Martín, Mendoza",
    year: "2024",
    highlight: "Sincronización en tiempo real de 3 cajas, +4.500 productos y facturación ARCA automática",
    rating: 5,
    testimonial: "El sistema Eleventa con la facturación ARCA de FactuTec es un cañón. Las 3 cajas comparten stock al instante y no se traba nunca."
  },
  {
    id: "supermercado-el-trebol",
    name: "Supermercado El Trébol",
    category: "almacenes",
    categoryName: "Comercios & Almacenes",
    logoText: "SET",
    logoColor: "#047857",
    logoBg: "#d1fae5",
    systemInstalled: "Eleventa + Facturación ARCA Automática",
    hardware: "2 Cajas Rápidas + Balanza Digital Systel",
    location: "Junín, Mendoza",
    year: "2023",
    highlight: "Conexión directa con balanza para productos a granel y facturación ARCA en cada ticket",
    rating: 5,
    testimonial: "Excelente atención de Joel y Emanuel. Nos dejaron las básculas y las impresoras configuradas funcionando de diez."
  },
  {
    id: "ferreteria-industrial-este",
    name: "Ferretería Industrial Este",
    category: "ferreterias",
    categoryName: "Ferreterías & Corralones",
    logoText: "FIE",
    logoColor: "#b45309",
    logoBg: "#fef3c7",
    systemInstalled: "Eleventa Avanzado MultiCaja + Factura A4",
    hardware: "Servidor Mostrador + 2 Terminales + Impresora A4",
    location: "Rivadavia, Mendoza",
    year: "2024",
    highlight: "Múltiples listas de precios, cuentas corrientes y módulo de facturas A4 para órdenes de compra",
    rating: 5,
    testimonial: "El módulo para emitir órdenes de compra y facturas en hoja A4 nos vino perfecto para las empresas que nos compran."
  },
  {
    id: "boutique-urbana",
    name: "Boutique Urbana Moda",
    category: "indumentaria",
    categoryName: "Indumentaria & Calzado",
    logoText: "BUM",
    logoColor: "#be185d",
    logoBg: "#fce7f3",
    systemInstalled: "Eleventa Básico ($200.000)",
    hardware: "1 Puesto Mostrador + Lector de Código de Barras",
    location: "San Martín Centro, Mendoza",
    year: "2024",
    highlight: "Control de inventario de indumentaria, cortes de caja por turno y operación 100% offline",
    rating: 5,
    testimonial: "Super fácil de usar. Pagamos los $200.000 una sola vez y nos olvidamos para siempre de pagar mensualidades."
  },
  {
    id: "corralon-mendoza",
    name: "Corralón Mendoza Materiales",
    category: "ferreterias",
    categoryName: "Ferreterías & Corralones",
    logoText: "CMM",
    logoColor: "#c2410c",
    logoBg: "#ffedd5",
    systemInstalled: "Eleventa Avanzado + ARCA + Red de Cajas",
    hardware: "4 Puestos en Red + Router Wi-Fi Comercial + 2 Impresoras",
    location: "Palmira, Mendoza",
    year: "2023",
    highlight: "Red local cableada por FactuTec con facturación electrónica ARCA automática en todas las cajas",
    rating: 5,
    testimonial: "FactuTec nos hizo no solo la instalación de Eleventa sino todo el cableado de red y configuración de routers."
  },
  {
    id: "pizzeria-donatello",
    name: "Pizzería & Resto Donatello",
    category: "gastronomia",
    categoryName: "Gastronomía & Bares",
    logoText: "PRD",
    logoColor: "#b91c1c",
    logoBg: "#fee2e2",
    systemInstalled: "Eleventa + Facturación ARCA",
    hardware: "PC Mostrador + Impresora Térmica 80mm",
    location: "San Martín, Mendoza",
    year: "2024",
    highlight: "Cortes de caja diarios exactos y facturación electrónica instantánea para delivery y salón",
    rating: 5,
    testimonial: "La velocidad de cobro los fines de semana es tremenda. La instalación fue impecable."
  },
  {
    id: "mayorista-los-andes",
    name: "Mayorista Los Andes",
    category: "mayoristas",
    categoryName: "Mayoristas & Distribuidoras",
    logoText: "MLA",
    logoColor: "#4338ca",
    logoBg: "#e0e7ff",
    systemInstalled: "Eleventa MultiCaja + ARCA + Factura A4",
    hardware: "5 Cajas en Red + Servidor Dedicado + Backup",
    location: "Godoy Cruz, Mendoza",
    year: "2023",
    highlight: "Sincronización multi-caja en tiempo real con facturación masiva ARCA",
    rating: 5,
    testimonial: "Emanuel y Joel nos armaron la red completa. El monitoreo remoto desde el celular nos permite ver las ventas en vivo."
  },
  {
    id: "autoservicio-san-cayetano",
    name: "Autoservicio San Cayetano",
    category: "almacenes",
    categoryName: "Comercios & Almacenes",
    logoText: "ASC",
    logoColor: "#059669",
    logoBg: "#ecfdf5",
    systemInstalled: "Eleventa Básico + Báscula",
    hardware: "Caja Principal + Lector Omnidireccional + Balanza",
    location: "Santa Rosa, Mendoza",
    year: "2024",
    highlight: "Control de entradas/salidas de mercadería y gestión de permisos por cajero",
    rating: 5,
    testimonial: "Nos ordenó las cajas por completo. El soporte por WhatsApp ante cualquier duda responde al toque."
  },
  {
    id: "repuestos-este",
    name: "Repuestos del Este Automotor",
    category: "servicios",
    categoryName: "Servicios & Repuestos",
    logoText: "REA",
    logoColor: "#0f766e",
    logoBg: "#ccfbf1",
    systemInstalled: "Eleventa Avanzado + Facturación ARCA",
    hardware: "2 Puestos de Mostrador + Impresora Fiscal",
    location: "San Martín, Mendoza",
    year: "2023",
    highlight: "Control de stock de miles de repuestos y facturación electrónica inmediata",
    rating: 5,
    testimonial: "Encontramos repuestos en segundos y cada venta queda registrada en ARCA sin pasos extras."
  },
  {
    id: "vinoteca-valle-este",
    name: "Vinoteca Valle del Este",
    category: "almacenes",
    categoryName: "Comercios & Almacenes",
    logoText: "VVE",
    logoColor: "#701a75",
    logoBg: "#fae8ff",
    systemInstalled: "Eleventa Básico ($200.000)",
    hardware: "PC All-in-One + Lector Inalámbrico",
    location: "Rivadavia, Mendoza",
    year: "2024",
    highlight: "Manejo de múltiples listas de precios y promociones",
    rating: 5,
    testimonial: "Muy estético y super fácil de aprender. En una tarde ya estábamos vendiendo."
  },
  {
    id: "libreria-san-martin",
    name: "Librería & Papelería Central",
    category: "almacenes",
    categoryName: "Comercios & Almacenes",
    logoText: "LPC",
    logoColor: "#0284c7",
    logoBg: "#e0f2fe",
    systemInstalled: "Eleventa + Facturación ARCA ($400.000)",
    hardware: "2 Cajas + Lector de Código de Barras + Impresora",
    location: "San Martín, Mendoza",
    year: "2024",
    highlight: "Factura electrónica ARCA automática y actualización de precios por Excel",
    rating: 5,
    testimonial: "La actualización de precios por Excel y la facturación ARCA automática nos ahorran horas de laburo."
  },
  {
    id: "cerveceria-artesanal",
    name: "Cervecería & Bar La Estación",
    category: "gastronomia",
    categoryName: "Gastronomía & Bares",
    logoText: "CBE",
    logoColor: "#d97706",
    logoBg: "#fef3c7",
    systemInstalled: "Eleventa MultiCaja + Red Wi-Fi",
    hardware: "Terminal Mostrador + Caja Barra + Red de Cajas",
    location: "Junín, Mendoza",
    year: "2024",
    highlight: "Gestión de cajas independientes con administración y precios centralizados",
    rating: 5,
    testimonial: "El sistema no falla nunca en pleno servicio nocturno. Una tranquilidad total."
  }
];
